name = "Dunst"
path = "~/.config/dunst/dunstrc"
formatter = """
[urgency_low]
    background  = "{HEX0}"
    foreground  = "{HEX7}"
    frame_color = "{HEX7}"

[urgency_normal]
    background  = "{HEX0}"
    foreground  = "{HEX15}"
    frame_color = "{HEX15}"

[urgency_critical]
    background  = "{HEX0}"
    foreground  = "{ACCHEX}"
    frame_color = "{ACCHEX}"
"""
