name = "Dwarf Fortress"
path = "colors.txt"
formatter = """
[BLACK_R:{R0}]
[BLACK_G:{G0}]
[BLACK_B:{B0}]
[RED_R:{R1}]
[RED_G:{G1}]
[RED_B:{B1}]
[GREEN_R:{R2}]
[GREEN_G:{G2}]
[GREEN_B:{B2}]
[BROWN_R:{R3}]
[BROWN_G:{G3}]
[BROWN_B:{B3}]
[BLUE_R:{R4}]
[BLUE_G:{G4}]
[BLUE_B:{B4}]
[MAGENTA_R:{R5}]
[MAGENTA_G:{G5}]
[MAGENTA_B:{B5}]
[CYAN_R:{R6}]
[CYAN_G:{G6}]
[CYAN_B:{B6}]
[LGRAY_R:{R7}]
[LGRAY_G:{G7}]
[LGRAY_B:{B7}]
[DGRAY_R:{R8}]
[DGRAY_G:{G8}]
[DGRAY_B:{B8}]
[LRED_R:{R9}]
[LRED_G:{G9}]
[LRED_B:{B9}]
[LGREEN_R:{R10}]
[LGREEN_G:{G10}]
[LGREEN_B:{B10}]
[YELLOW_R:{R11}]
[YELLOW_G:{G11}]
[YELLOW_B:{B11}]
[LBLUE_R:{R12}]
[LBLUE_G:{G12}]
[LBLUE_B:{B12}]
[LMAGENTA_R:{R13}]
[LMAGENTA_G:{G13}]
[LMAGENTA_B:{B13}]
[LCYAN_R:{R14}]
[LCYAN_G:{G14}]
[LCYAN_B:{B14}]
[WHITE_R:{R15}]
[WHITE_G:{G15}]
[WHITE_B:{B15}]
"""
