name = "PPM"
formatter = """
P3 8 2 255
{R0} {G0} {B0}
{R1} {G1} {B1}
{R2} {G2} {B2}
{R3} {G3} {B3}
{R4} {G4} {B4}
{R5} {G5} {B5}
{R6} {G6} {B6}
{R7} {G7} {B7}
{R8} {G8} {B8}
{R9} {G9} {B9}
{R10} {G10} {B10}
{R11} {G11} {B11}
{R12} {G12} {B12}
{R13} {G13} {B13}
{R14} {G14} {B14}
{R15} {G15} {B15}
"""
path = "collurgy.toml"
